/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MapView, PluginDefinitions } from "./components/gwf-vis-host/gwf-vis-host";
export namespace Components {
    interface GwfVisHost {
        "imports": { [name: string]: string };
        "plugins": PluginDefinitions;
        "preferCanvas": boolean;
        "serverFileApiBasePath": string;
        "view": MapView;
    }
    interface GwfVisHostCollapse {
        "collapsed": boolean;
    }
    interface GwfVisHostMainItemContainer {
        "containerProps"?: { width?: string };
        "header": string;
    }
    interface GwfVisHostSidebar {
        "active": boolean;
    }
    interface GwfVisHostSidebarItemContainer {
        "containerProps"?: { slot?: string };
        "header": string;
    }
}
declare global {
    interface HTMLGwfVisHostElement extends Components.GwfVisHost, HTMLStencilElement {
    }
    var HTMLGwfVisHostElement: {
        prototype: HTMLGwfVisHostElement;
        new (): HTMLGwfVisHostElement;
    };
    interface HTMLGwfVisHostCollapseElement extends Components.GwfVisHostCollapse, HTMLStencilElement {
    }
    var HTMLGwfVisHostCollapseElement: {
        prototype: HTMLGwfVisHostCollapseElement;
        new (): HTMLGwfVisHostCollapseElement;
    };
    interface HTMLGwfVisHostMainItemContainerElement extends Components.GwfVisHostMainItemContainer, HTMLStencilElement {
    }
    var HTMLGwfVisHostMainItemContainerElement: {
        prototype: HTMLGwfVisHostMainItemContainerElement;
        new (): HTMLGwfVisHostMainItemContainerElement;
    };
    interface HTMLGwfVisHostSidebarElement extends Components.GwfVisHostSidebar, HTMLStencilElement {
    }
    var HTMLGwfVisHostSidebarElement: {
        prototype: HTMLGwfVisHostSidebarElement;
        new (): HTMLGwfVisHostSidebarElement;
    };
    interface HTMLGwfVisHostSidebarItemContainerElement extends Components.GwfVisHostSidebarItemContainer, HTMLStencilElement {
    }
    var HTMLGwfVisHostSidebarItemContainerElement: {
        prototype: HTMLGwfVisHostSidebarItemContainerElement;
        new (): HTMLGwfVisHostSidebarItemContainerElement;
    };
    interface HTMLElementTagNameMap {
        "gwf-vis-host": HTMLGwfVisHostElement;
        "gwf-vis-host-collapse": HTMLGwfVisHostCollapseElement;
        "gwf-vis-host-main-item-container": HTMLGwfVisHostMainItemContainerElement;
        "gwf-vis-host-sidebar": HTMLGwfVisHostSidebarElement;
        "gwf-vis-host-sidebar-item-container": HTMLGwfVisHostSidebarItemContainerElement;
    }
}
declare namespace LocalJSX {
    interface GwfVisHost {
        "imports"?: { [name: string]: string };
        "plugins"?: PluginDefinitions;
        "preferCanvas"?: boolean;
        "serverFileApiBasePath"?: string;
        "view"?: MapView;
    }
    interface GwfVisHostCollapse {
        "collapsed"?: boolean;
    }
    interface GwfVisHostMainItemContainer {
        "containerProps"?: { width?: string };
        "header"?: string;
    }
    interface GwfVisHostSidebar {
        "active"?: boolean;
    }
    interface GwfVisHostSidebarItemContainer {
        "containerProps"?: { slot?: string };
        "header"?: string;
    }
    interface IntrinsicElements {
        "gwf-vis-host": GwfVisHost;
        "gwf-vis-host-collapse": GwfVisHostCollapse;
        "gwf-vis-host-main-item-container": GwfVisHostMainItemContainer;
        "gwf-vis-host-sidebar": GwfVisHostSidebar;
        "gwf-vis-host-sidebar-item-container": GwfVisHostSidebarItemContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gwf-vis-host": LocalJSX.GwfVisHost & JSXBase.HTMLAttributes<HTMLGwfVisHostElement>;
            "gwf-vis-host-collapse": LocalJSX.GwfVisHostCollapse & JSXBase.HTMLAttributes<HTMLGwfVisHostCollapseElement>;
            "gwf-vis-host-main-item-container": LocalJSX.GwfVisHostMainItemContainer & JSXBase.HTMLAttributes<HTMLGwfVisHostMainItemContainerElement>;
            "gwf-vis-host-sidebar": LocalJSX.GwfVisHostSidebar & JSXBase.HTMLAttributes<HTMLGwfVisHostSidebarElement>;
            "gwf-vis-host-sidebar-item-container": LocalJSX.GwfVisHostSidebarItemContainer & JSXBase.HTMLAttributes<HTMLGwfVisHostSidebarItemContainerElement>;
        }
    }
}
