/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TreeNode } from "./components/app-tree-view/app-tree-view";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppSignIn {
    }
    interface AppTreeView {
        "data"?: TreeNode;
    }
    interface AppVis {
        "pluginUrl": string;
        "user": string;
        "visId": string;
    }
}
export interface AppTreeViewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppTreeViewElement;
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSignInElement extends Components.AppSignIn, HTMLStencilElement {
    }
    var HTMLAppSignInElement: {
        prototype: HTMLAppSignInElement;
        new (): HTMLAppSignInElement;
    };
    interface HTMLAppTreeViewElement extends Components.AppTreeView, HTMLStencilElement {
    }
    var HTMLAppTreeViewElement: {
        prototype: HTMLAppTreeViewElement;
        new (): HTMLAppTreeViewElement;
    };
    interface HTMLAppVisElement extends Components.AppVis, HTMLStencilElement {
    }
    var HTMLAppVisElement: {
        prototype: HTMLAppVisElement;
        new (): HTMLAppVisElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-sign-in": HTMLAppSignInElement;
        "app-tree-view": HTMLAppTreeViewElement;
        "app-vis": HTMLAppVisElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppSignIn {
    }
    interface AppTreeView {
        "data"?: TreeNode;
        "onItemClicked"?: (event: AppTreeViewCustomEvent<TreeNode>) => void;
        "onItemRightClicked"?: (event: AppTreeViewCustomEvent<TreeNode>) => void;
    }
    interface AppVis {
        "pluginUrl"?: string;
        "user"?: string;
        "visId"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-sign-in": AppSignIn;
        "app-tree-view": AppTreeView;
        "app-vis": AppVis;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-sign-in": LocalJSX.AppSignIn & JSXBase.HTMLAttributes<HTMLAppSignInElement>;
            "app-tree-view": LocalJSX.AppTreeView & JSXBase.HTMLAttributes<HTMLAppTreeViewElement>;
            "app-vis": LocalJSX.AppVis & JSXBase.HTMLAttributes<HTMLAppVisElement>;
        }
    }
}
